name: Build gbinterceptor firmware
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Clone pico-sdk dependency
        run: |
          git clone https://github.com/raspberrypi/pico-sdk --recurse-submodules
      - name: Build firmware
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        run: |
          arm-none-eabi-gcc --version
          cd ./firmware
          mkdir build && cd build
          cmake .. -G Ninja -DPICO_SDK_PATH=../../pico-sdk
          ninja
