name: Build gbinterceptor firmware
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build firmware
        run: |
          apt install arm-none-eabi-gcc
          git clone https://github.com/raspberrypi/pico-sdk --recurse-submodules
          cd ./firmware
          mkdir build && cd build
          cmake .. -G Ninja -DPICO_SDK_PATH=../../pico-sdk
          ninja
